EmployeeManagementMVC/EmployeeManagementMVC/Models/EMPLOYEE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.DEPARTMENTS = new HashSet<DEPARTMENT>();
            this.EMPLOYEES1 = new HashSet<EMPLOYEE>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        [Required(ErrorMessage = "FIRST_NAME is required")]
        public string FIRST_NAME { get; set; }
        [Required(ErrorMessage = "LAST_NAME is required")]
        public string LAST_NAME { get; set; }
        [Required(ErrorMessage = "EMAIL is required")]
        public string EMAIL { get; set; }
        public string PHONE_NUMBER { get; set; }
        public System.DateTime HIRE_DATE { get; set; }
        public string JOB_ID { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> COMMISSION_PCT { get; set; }
        public Nullable<int> MANAGER_ID { get; set; }
        public Nullable<short> DEPARTMENT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTMENT> DEPARTMENTS { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual JOB JOB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEES1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
    }
}

EmployeeManagementMVC/EmployeeManagementMVC/Controllers/EMPLOYEEController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmployeeManagementMVC.Models;

namespace EmployeeManagementMVC.Controllers
{
    public class EMPLOYEEController : Controller
    {
        private EmployeeEntities db = new EmployeeEntities();


        //Go to Login page
        public ActionResult Login()
        {
            return View();
        }

        //post to login to index page
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login( int MANAGER_ID)
        {
            Session["ID"] = MANAGER_ID;
            int Login_Id = Convert.ToInt32(Session["ID"]);
            return RedirectToAction("Index",new {id = Login_Id});
        }

        // GET: EMPLOYEE
        public ActionResult Index(int? ID)
        {
            if(ID == null)
            {
                return Content("You must enter a Login Id");
            }
            var eMPLOYEES = db.EMPLOYEES.Include(e => e.DEPARTMENT).Include(e => e.EMPLOYEE1).Where(e => e.MANAGER_ID==ID);
            //var eMPLOYEES = db.EMPLOYEES.Where(e => e.MANAGER_ID==MANAGER_ID);
            return View(eMPLOYEES.ToList());
        }

        // GET: EMPLOYEE/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE eMPLOYEE = db.EMPLOYEES.Find(id);
            if (eMPLOYEE == null)
            {
                return HttpNotFound();
            }
            return View(eMPLOYEE);
        }

        // GET: EMPLOYEE/Create
        public ActionResult Create()
        {
            ViewBag.DEPARTMENT_ID = new SelectList(db.DEPARTMENTS, "DEPARTMENT_ID", "DEPARTMENT_NAME");
            return View();
        }

        // POST: EMPLOYEE/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,DEPARTMENT_ID")] EMPLOYEE eMPLOYEE)
        {
            int Login_Id = Convert.ToInt32(Session["ID"]);
            if (ModelState.IsValid)
            {
                eMPLOYEE.MANAGER_ID = Login_Id;
                db.EMPLOYEES.Add(eMPLOYEE);
                db.SaveChanges();
                return RedirectToAction("Index", new {id = Login_Id });
            }

            ViewBag.DEPARTMENT_ID = new SelectList(db.DEPARTMENTS, "DEPARTMENT_ID", "DEPARTMENT_NAME", eMPLOYEE.DEPARTMENT_ID);
            ViewBag.MANAGER_ID = new SelectList(db.EMPLOYEES, "EMPLOYEE_ID", "FIRST_NAME", eMPLOYEE.MANAGER_ID);
            return View(eMPLOYEE);
        }

        // GET: EMPLOYEE/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE eMPLOYEE = db.EMPLOYEES.Find(id);
            if (eMPLOYEE == null)
            {
                return HttpNotFound();
            }
            ViewBag.DEPARTMENT_ID = new SelectList(db.DEPARTMENTS, "DEPARTMENT_ID", "DEPARTMENT_NAME", eMPLOYEE.DEPARTMENT_ID);
            ViewBag.MANAGER_ID = new SelectList(db.EMPLOYEES, "EMPLOYEE_ID", "FIRST_NAME", eMPLOYEE.MANAGER_ID);
            return View(eMPLOYEE);
        }

        // POST: EMPLOYEE/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID")] EMPLOYEE eMPLOYEE)
        {
            int Login_Id = Convert.ToInt32(Session["ID"]);
            if (ModelState.IsValid)
            {
                db.Entry(eMPLOYEE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = Login_Id});
            }
            ViewBag.DEPARTMENT_ID = new SelectList(db.DEPARTMENTS, "DEPARTMENT_ID", "DEPARTMENT_NAME", eMPLOYEE.DEPARTMENT_ID);
            ViewBag.MANAGER_ID = new SelectList(db.EMPLOYEES, "EMPLOYEE_ID", "FIRST_NAME", eMPLOYEE.MANAGER_ID);
            return View(eMPLOYEE);
        }

        // GET: EMPLOYEE/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE eMPLOYEE = db.EMPLOYEES.Find(id);
            if (eMPLOYEE == null)
            {
                return HttpNotFound();
            }
            return View(eMPLOYEE);
        }

        // POST: EMPLOYEE/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int Login_Id = Convert.ToInt32(Session["ID"]);
            EMPLOYEE eMPLOYEE = db.EMPLOYEES.Find(id);
            db.EMPLOYEES.Remove(eMPLOYEE);
            db.SaveChanges();
            return RedirectToAction("Index",new { id = Login_Id});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EmployeeManagementMVC/EmployeeManagementMVC/Views/EMPLOYEE/Create.cshtml
@model EmployeeManagementMVC.Models.EMPLOYEE

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>EMPLOYEE</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
            <div class="form-group">
                @Html.LabelFor(model => model.FIRST_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FIRST_NAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FIRST_NAME, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LAST_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LAST_NAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LAST_NAME, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PHONE_NUMBER, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PHONE_NUMBER, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PHONE_NUMBER, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.HIRE_DATE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HIRE_DATE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HIRE_DATE, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.JOB_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.JOB_ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.JOB_ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SALARY, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SALARY, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SALARY, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.COMMISSION_PCT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.COMMISSION_PCT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.COMMISSION_PCT, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DEPARTMENT_ID, "DEPARTMENT_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DEPARTMENT_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DEPARTMENT_ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

EmployeeManagementMVC/EmployeeManagementMVC/Views/EMPLOYEE/Delete.cshtml
@model EmployeeManagementMVC.Models.EMPLOYEE

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>EMPLOYEE</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FIRST_NAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FIRST_NAME)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LAST_NAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LAST_NAME)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EMAIL)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EMAIL)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PHONE_NUMBER)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PHONE_NUMBER)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.HIRE_DATE)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.HIRE_DATE)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.JOB_ID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.JOB_ID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SALARY)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SALARY)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.COMMISSION_PCT)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.COMMISSION_PCT)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DEPARTMENT.DEPARTMENT_NAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DEPARTMENT.DEPARTMENT_NAME)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EMPLOYEE1.FIRST_NAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EMPLOYEE1.FIRST_NAME)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index", new {id = Model.MANAGER_ID })
            </div>
        }
    </div>
</body>
</html>

EmployeeManagementMVC/EmployeeManagementMVC/Views/EMPLOYEE/Details.cshtml
@model EmployeeManagementMVC.Models.EMPLOYEE

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>EMPLOYEE</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FIRST_NAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FIRST_NAME)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LAST_NAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LAST_NAME)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EMAIL)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EMAIL)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PHONE_NUMBER)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PHONE_NUMBER)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.HIRE_DATE)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.HIRE_DATE)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.JOB_ID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.JOB_ID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SALARY)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SALARY)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.COMMISSION_PCT)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.COMMISSION_PCT)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DEPARTMENT.DEPARTMENT_NAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DEPARTMENT.DEPARTMENT_NAME)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EMPLOYEE1.FIRST_NAME)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EMPLOYEE1.FIRST_NAME)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.EMPLOYEE_ID }) |
        @Html.ActionLink("Back to List", "Index", new { id = Model.MANAGER_ID})
    </p>
</body>
</html>

EmployeeManagementMVC/EmployeeManagementMVC/Views/EMPLOYEE/Edit.cshtml
@model EmployeeManagementMVC.Models.EMPLOYEE

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>EMPLOYEE</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.EMPLOYEE_ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.FIRST_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FIRST_NAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FIRST_NAME, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LAST_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LAST_NAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LAST_NAME, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PHONE_NUMBER, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PHONE_NUMBER, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PHONE_NUMBER, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.HIRE_DATE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HIRE_DATE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HIRE_DATE, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.JOB_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.JOB_ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.JOB_ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SALARY, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SALARY, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SALARY, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.COMMISSION_PCT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.COMMISSION_PCT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.COMMISSION_PCT, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.MANAGER_ID, "MANAGER_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MANAGER_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MANAGER_ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DEPARTMENT_ID, "DEPARTMENT_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DEPARTMENT_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DEPARTMENT_ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index", new {id = Model.MANAGER_ID })
    </div>
</body>
</html>

EmployeeManagementMVC/EmployeeManagementMVC/Views/EMPLOYEE/Login.cshtml
@model EmployeeManagementMVC.Models.EMPLOYEE
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h2>Login</h2>

    <h3>Click on Register tab and complete form to get an login ID</h3>
    <h3>Enter your Login ID and click submit</h3>
    
    @using (Html.BeginForm("Login", "EMPLOYEE", FormMethod.Post, new { id = "login_form" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <!-- @Html.LabelFor(model => model.EMPLOYEE_ID, htmlAttributes: new { @class = "control-label col-md-2" })-->
                @Html.Label("MANAGER_ID","LOGIN ID", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <!--@Html.EditorFor(model => model.EMPLOYEE_ID, new { htmlAttributes = new { @class = "form-control" } })-->
                    @Html.Editor("MANAGER_ID", new { @class = "form-control" })
                    @Html.ValidationMessage("MANAGER_ID", "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Back to Home Page", "Index")
    </div>
</div>